
package com.roojai.radar.stubMotor;

import grails.util.Environment;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DpoService", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", wsdlLocation = "file:/C:/Dev/webservice/DpoService.wsdl")
public class DpoService_Service
    extends Service
{

    private final static URL DPOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DPOSERVICE_EXCEPTION;
    private final static QName DPOSERVICE_QNAME = new QName("http://towerswatson.com/rto/dpo/services/2010/01", "DpoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if( Environment.isDevelopmentMode() ){
        		url = new URL("file:MotorCycleDpoService.wsdl"); // for dev only
        	}else{
        		url =  new URL("classpath:MotorCycleDpoService.wsdl");//for production and uat
        	} 
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DPOSERVICE_WSDL_LOCATION = url;
        DPOSERVICE_EXCEPTION = e;
    }

    public DpoService_Service() {
        super(__getWsdlLocation(), DPOSERVICE_QNAME);
    }

    public DpoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DPOSERVICE_QNAME, features);
    }

    public DpoService_Service(URL wsdlLocation) {
        super(wsdlLocation, DPOSERVICE_QNAME);
    }

    public DpoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DPOSERVICE_QNAME, features);
    }

    public DpoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DpoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DpoService
     */
    @WebEndpoint(name = "DefaultDpoServiceEndpoint1")
    public DpoService getDefaultDpoServiceEndpoint1() {
        return super.getPort(new QName("http://towerswatson.com/rto/dpo/services/2010/01", "DefaultDpoServiceEndpoint1"), DpoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DpoService
     */
    @WebEndpoint(name = "DefaultDpoServiceEndpoint1")
    public DpoService getDefaultDpoServiceEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://towerswatson.com/rto/dpo/services/2010/01", "DefaultDpoServiceEndpoint1"), DpoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DPOSERVICE_EXCEPTION!= null) {
            throw DPOSERVICE_EXCEPTION;
        }
        return DPOSERVICE_WSDL_LOCATION;
    }

}
