//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 01:28:19 PM ICT 
//


package com.roojai.radar.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     *
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Quote }
     *
     */
    public Root.Quote createRootQuote() {
        return new Root.Quote();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyStartDate }
     *
     */
    public Root.Quote.PolicyStartDate createRootQuotePolicyStartDate() {
        return new Root.Quote.PolicyStartDate();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyEndDate }
     *
     */
    public Root.Quote.PolicyEndDate createRootQuotePolicyEndDate() {
        return new Root.Quote.PolicyEndDate();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyQuoteExpiryDate }
     *
     */
    public Root.Quote.PolicyQuoteExpiryDate createRootQuotePolicyQuoteExpiryDate() {
        return new Root.Quote.PolicyQuoteExpiryDate();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyNumber }
     *
     */
    public Root.Quote.PolicyNumber createRootQuotePolicyNumber() {
        return new Root.Quote.PolicyNumber();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyStatus }
     *
     */
    public Root.Quote.PolicyStatus createRootQuotePolicyStatus() {
        return new Root.Quote.PolicyStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyPromoCode }
     *
     */
    public Root.Quote.PolicyPromoCode createRootQuotePolicyPromoCode() {
        return new Root.Quote.PolicyPromoCode();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyPreviousCoverType }
     *
     */
    public Root.Quote.PolicyPreviousCoverType createRootQuotePolicyPreviousCoverType() {
        return new Root.Quote.PolicyPreviousCoverType();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyAutoRenewalFlag }
     *
     */
    public Root.Quote.PolicyAutoRenewalFlag createRootQuotePolicyAutoRenewalFlag() {
        return new Root.Quote.PolicyAutoRenewalFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyFacebookShareFlag }
     *
     */
    public Root.Quote.PolicyFacebookShareFlag createRootQuotePolicyFacebookShareFlag() {
        return new Root.Quote.PolicyFacebookShareFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyPaymentMethod }
     *
     */
    public Root.Quote.PolicyPaymentMethod createRootQuotePolicyPaymentMethod() {
        return new Root.Quote.PolicyPaymentMethod();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyPaymentFrequency }
     *
     */
    public Root.Quote.PolicyPaymentFrequency createRootQuotePolicyPaymentFrequency() {
        return new Root.Quote.PolicyPaymentFrequency();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyProductVersion }
     *
     */
    public Root.Quote.PolicyProductVersion createRootQuotePolicyProductVersion() {
        return new Root.Quote.PolicyProductVersion();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderIsDriving }
     *
     */
    public Root.Quote.PolicyholderIsDriving createRootQuotePolicyholderIsDriving() {
        return new Root.Quote.PolicyholderIsDriving();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderDeclaredNCB }
     *
     */
    public Root.Quote.PolicyholderDeclaredNCB createRootQuotePolicyholderDeclaredNCB() {
        return new Root.Quote.PolicyholderDeclaredNCB();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderYearsOfInsurance }
     *
     */
    public Root.Quote.PolicyholderYearsOfInsurance createRootQuotePolicyholderYearsOfInsurance() {
        return new Root.Quote.PolicyholderYearsOfInsurance();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderClaimExperience }
     *
     */
    public Root.Quote.PolicyholderClaimExperience createRootQuotePolicyholderClaimExperience() {
        return new Root.Quote.PolicyholderClaimExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderDerivedNCB }
     *
     */
    public Root.Quote.PolicyholderDerivedNCB createRootQuotePolicyholderDerivedNCB() {
        return new Root.Quote.PolicyholderDerivedNCB();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderHouseholdNbCars }
     *
     */
    public Root.Quote.PolicyholderHouseholdNbCars createRootQuotePolicyholderHouseholdNbCars() {
        return new Root.Quote.PolicyholderHouseholdNbCars();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderHomePostalCode }
     *
     */
    public Root.Quote.PolicyholderHomePostalCode createRootQuotePolicyholderHomePostalCode() {
        return new Root.Quote.PolicyholderHomePostalCode();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderOfficePostalCode }
     *
     */
    public Root.Quote.PolicyholderOfficePostalCode createRootQuotePolicyholderOfficePostalCode() {
        return new Root.Quote.PolicyholderOfficePostalCode();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderCarFinancingMethod }
     *
     */
    public Root.Quote.PolicyholderCarFinancingMethod createRootQuotePolicyholderCarFinancingMethod() {
        return new Root.Quote.PolicyholderCarFinancingMethod();
    }

    /**
     * Create an instance of {@link Root.Quote.CarManufactureYear }
     *
     */
    public Root.Quote.CarManufactureYear createRootQuoteCarManufactureYear() {
        return new Root.Quote.CarManufactureYear();
    }

    /**
     * Create an instance of {@link Root.Quote.CarTransmission }
     *
     */
    public Root.Quote.CarTransmission createRootQuoteCarTransmission() {
        return new Root.Quote.CarTransmission();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCubicCapacity }
     *
     */
    public Root.Quote.CarCubicCapacity createRootQuoteCarCubicCapacity() {
        return new Root.Quote.CarCubicCapacity();
    }

    /**
     * Create an instance of {@link Root.Quote.CarModelIsNotKnown }
     *
     */
    public Root.Quote.CarModelIsNotKnown createRootQuoteCarModelIsNotKnown() {
        return new Root.Quote.CarModelIsNotKnown();
    }

    /**
     * Create an instance of {@link Root.Quote.CarDefaultValue }
     *
     */
    public Root.Quote.CarDefaultValue createRootQuoteCarDefaultValue() {
        return new Root.Quote.CarDefaultValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAdjustedValue }
     *
     */
    public Root.Quote.CarAdjustedValue createRootQuoteCarAdjustedValue() {
        return new Root.Quote.CarAdjustedValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarValue }
     *
     */
    public Root.Quote.CarValue createRootQuoteCarValue() {
        return new Root.Quote.CarValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarTypeVoluntaryInsurance }
     *
     */
    public Root.Quote.CarTypeVoluntaryInsurance createRootQuoteCarTypeVoluntaryInsurance() {
        return new Root.Quote.CarTypeVoluntaryInsurance();
    }

    /**
     * Create an instance of {@link Root.Quote.CarNbSeats }
     *
     */
    public Root.Quote.CarNbSeats createRootQuoteCarNbSeats() {
        return new Root.Quote.CarNbSeats();
    }

    /**
     * Create an instance of {@link Root.Quote.CarMileage }
     *
     */
    public Root.Quote.CarMileage createRootQuoteCarMileage() {
        return new Root.Quote.CarMileage();
    }

    /**
     * Create an instance of {@link Root.Quote.CarIsModified }
     *
     */
    public Root.Quote.CarIsModified createRootQuoteCarIsModified() {
        return new Root.Quote.CarIsModified();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryTotalValue }
     *
     */
    public Root.Quote.CarAccessoryTotalValue createRootQuoteCarAccessoryTotalValue() {
        return new Root.Quote.CarAccessoryTotalValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCondition }
     *
     */
    public Root.Quote.CarCondition createRootQuoteCarCondition() {
        return new Root.Quote.CarCondition();
    }

    /**
     * Create an instance of {@link Root.Quote.CarParkingLocation }
     *
     */
    public Root.Quote.CarParkingLocation createRootQuoteCarParkingLocation() {
        return new Root.Quote.CarParkingLocation();
    }

    /**
     * Create an instance of {@link Root.Quote.CarDateOfOwnership }
     *
     */
    public Root.Quote.CarDateOfOwnership createRootQuoteCarDateOfOwnership() {
        return new Root.Quote.CarDateOfOwnership();
    }

    /**
     * Create an instance of {@link Root.Quote.CarOwnership }
     *
     */
    public Root.Quote.CarOwnership createRootQuoteCarOwnership() {
        return new Root.Quote.CarOwnership();
    }

    /**
     * Create an instance of {@link Root.Quote.CarOdometerReading }
     *
     */
    public Root.Quote.CarOdometerReading createRootQuoteCarOdometerReading() {
        return new Root.Quote.CarOdometerReading();
    }

    /**
     * Create an instance of {@link Root.Quote.CarIsRedPlate }
     *
     */
    public Root.Quote.CarIsRedPlate createRootQuoteCarIsRedPlate() {
        return new Root.Quote.CarIsRedPlate();
    }

    /**
     * Create an instance of {@link Root.Quote.CarPlateProvince }
     *
     */
    public Root.Quote.CarPlateProvince createRootQuoteCarPlateProvince() {
        return new Root.Quote.CarPlateProvince();
    }

    /**
     * Create an instance of {@link Root.Quote.CarPreviousInsurer }
     *
     */
    public Root.Quote.CarPreviousInsurer createRootQuoteCarPreviousInsurer() {
        return new Root.Quote.CarPreviousInsurer();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1Age }
     *
     */
    public Root.Quote.Driver1Age createRootQuoteDriver1Age() {
        return new Root.Quote.Driver1Age();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1MaritalStatus }
     *
     */
    public Root.Quote.Driver1MaritalStatus createRootQuoteDriver1MaritalStatus() {
        return new Root.Quote.Driver1MaritalStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1Gender }
     *
     */
    public Root.Quote.Driver1Gender createRootQuoteDriver1Gender() {
        return new Root.Quote.Driver1Gender();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1Occupation }
     *
     */
    public Root.Quote.Driver1Occupation createRootQuoteDriver1Occupation() {
        return new Root.Quote.Driver1Occupation();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1DrivingExperience }
     *
     */
    public Root.Quote.Driver1DrivingExperience createRootQuoteDriver1DrivingExperience() {
        return new Root.Quote.Driver1DrivingExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1Accidents }
     *
     */
    public Root.Quote.Driver1Accidents createRootQuoteDriver1Accidents() {
        return new Root.Quote.Driver1Accidents();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1IsMain }
     *
     */
    public Root.Quote.Driver1IsMain createRootQuoteDriver1IsMain() {
        return new Root.Quote.Driver1IsMain();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1YoungerThanMainFlag }
     *
     */
    public Root.Quote.Driver1YoungerThanMainFlag createRootQuoteDriver1YoungerThanMainFlag() {
        return new Root.Quote.Driver1YoungerThanMainFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2Age }
     *
     */
    public Root.Quote.Driver2Age createRootQuoteDriver2Age() {
        return new Root.Quote.Driver2Age();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2MaritalStatus }
     *
     */
    public Root.Quote.Driver2MaritalStatus createRootQuoteDriver2MaritalStatus() {
        return new Root.Quote.Driver2MaritalStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2Gender }
     *
     */
    public Root.Quote.Driver2Gender createRootQuoteDriver2Gender() {
        return new Root.Quote.Driver2Gender();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2Occupation }
     *
     */
    public Root.Quote.Driver2Occupation createRootQuoteDriver2Occupation() {
        return new Root.Quote.Driver2Occupation();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2DrivingExperience }
     *
     */
    public Root.Quote.Driver2DrivingExperience createRootQuoteDriver2DrivingExperience() {
        return new Root.Quote.Driver2DrivingExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2Accidents }
     *
     */
    public Root.Quote.Driver2Accidents createRootQuoteDriver2Accidents() {
        return new Root.Quote.Driver2Accidents();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2IsMain }
     *
     */
    public Root.Quote.Driver2IsMain createRootQuoteDriver2IsMain() {
        return new Root.Quote.Driver2IsMain();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2YoungerThanMainFlag }
     *
     */
    public Root.Quote.Driver2YoungerThanMainFlag createRootQuoteDriver2YoungerThanMainFlag() {
        return new Root.Quote.Driver2YoungerThanMainFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3Age }
     *
     */
    public Root.Quote.Driver3Age createRootQuoteDriver3Age() {
        return new Root.Quote.Driver3Age();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3MaritalStatus }
     *
     */
    public Root.Quote.Driver3MaritalStatus createRootQuoteDriver3MaritalStatus() {
        return new Root.Quote.Driver3MaritalStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3Gender }
     *
     */
    public Root.Quote.Driver3Gender createRootQuoteDriver3Gender() {
        return new Root.Quote.Driver3Gender();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3Occupation }
     *
     */
    public Root.Quote.Driver3Occupation createRootQuoteDriver3Occupation() {
        return new Root.Quote.Driver3Occupation();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3DrivingExperience }
     *
     */
    public Root.Quote.Driver3DrivingExperience createRootQuoteDriver3DrivingExperience() {
        return new Root.Quote.Driver3DrivingExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3Accidents }
     *
     */
    public Root.Quote.Driver3Accidents createRootQuoteDriver3Accidents() {
        return new Root.Quote.Driver3Accidents();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3IsMain }
     *
     */
    public Root.Quote.Driver3IsMain createRootQuoteDriver3IsMain() {
        return new Root.Quote.Driver3IsMain();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3YoungerThanMainFlag }
     *
     */
    public Root.Quote.Driver3YoungerThanMainFlag createRootQuoteDriver3YoungerThanMainFlag() {
        return new Root.Quote.Driver3YoungerThanMainFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4Age }
     *
     */
    public Root.Quote.Driver4Age createRootQuoteDriver4Age() {
        return new Root.Quote.Driver4Age();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4MaritalStatus }
     *
     */
    public Root.Quote.Driver4MaritalStatus createRootQuoteDriver4MaritalStatus() {
        return new Root.Quote.Driver4MaritalStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4Gender }
     *
     */
    public Root.Quote.Driver4Gender createRootQuoteDriver4Gender() {
        return new Root.Quote.Driver4Gender();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4Occupation }
     *
     */
    public Root.Quote.Driver4Occupation createRootQuoteDriver4Occupation() {
        return new Root.Quote.Driver4Occupation();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4DrivingExperience }
     *
     */
    public Root.Quote.Driver4DrivingExperience createRootQuoteDriver4DrivingExperience() {
        return new Root.Quote.Driver4DrivingExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4Accidents }
     *
     */
    public Root.Quote.Driver4Accidents createRootQuoteDriver4Accidents() {
        return new Root.Quote.Driver4Accidents();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4IsMain }
     *
     */
    public Root.Quote.Driver4IsMain createRootQuoteDriver4IsMain() {
        return new Root.Quote.Driver4IsMain();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4YoungerThanMainFlag }
     *
     */
    public Root.Quote.Driver4YoungerThanMainFlag createRootQuoteDriver4YoungerThanMainFlag() {
        return new Root.Quote.Driver4YoungerThanMainFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverVoluntaryType }
     *
     */
    public Root.Quote.CoverVoluntaryType createRootQuoteCoverVoluntaryType() {
        return new Root.Quote.CoverVoluntaryType();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODDeductibleAmount }
     *
     */
    public Root.Quote.CoverODDeductibleAmount createRootQuoteCoverODDeductibleAmount() {
        return new Root.Quote.CoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverWorkshopSelection }
     *
     */
    public Root.Quote.CoverWorkshopSelection createRootQuoteCoverWorkshopSelection() {
        return new Root.Quote.CoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverDriverPlan }
     *
     */
    public Root.Quote.CoverDriverPlan createRootQuoteCoverDriverPlan() {
        return new Root.Quote.CoverDriverPlan();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTerritorialSelection }
     *
     */
    public Root.Quote.CoverTerritorialSelection createRootQuoteCoverTerritorialSelection() {
        return new Root.Quote.CoverTerritorialSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverIncludesCompulsoryFlag }
     *
     */
    public Root.Quote.CoverIncludesCompulsoryFlag createRootQuoteCoverIncludesCompulsoryFlag() {
        return new Root.Quote.CoverIncludesCompulsoryFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODPersonalAccidentSI }
     *
     */
    public Root.Quote.CoverODPersonalAccidentSI createRootQuoteCoverODPersonalAccidentSI() {
        return new Root.Quote.CoverODPersonalAccidentSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODCollisionSI }
     *
     */
    public Root.Quote.CoverODCollisionSI createRootQuoteCoverODCollisionSI() {
        return new Root.Quote.CoverODCollisionSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODFireTheftSI }
     *
     */
    public Root.Quote.CoverODFireTheftSI createRootQuoteCoverODFireTheftSI() {
        return new Root.Quote.CoverODFireTheftSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODNaturalDisasterSI }
     *
     */
    public Root.Quote.CoverODNaturalDisasterSI createRootQuoteCoverODNaturalDisasterSI() {
        return new Root.Quote.CoverODNaturalDisasterSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryPropertyDamageSI }
     *
     */
    public Root.Quote.CoverTPVoluntaryPropertyDamageSI createRootQuoteCoverTPVoluntaryPropertyDamageSI() {
        return new Root.Quote.CoverTPVoluntaryPropertyDamageSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryBodilyInjurySI }
     *
     */
    public Root.Quote.CoverTPVoluntaryBodilyInjurySI createRootQuoteCoverTPVoluntaryBodilyInjurySI() {
        return new Root.Quote.CoverTPVoluntaryBodilyInjurySI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverWindscreenSI }
     *
     */
    public Root.Quote.CoverWindscreenSI createRootQuoteCoverWindscreenSI() {
        return new Root.Quote.CoverWindscreenSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPADriversSI }
     *
     */
    public Root.Quote.CoverPADriversSI createRootQuoteCoverPADriversSI() {
        return new Root.Quote.CoverPADriversSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPAPassengersSI }
     *
     */
    public Root.Quote.CoverPAPassengersSI createRootQuoteCoverPAPassengersSI() {
        return new Root.Quote.CoverPAPassengersSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverMedicalExpensesSI }
     *
     */
    public Root.Quote.CoverMedicalExpensesSI createRootQuoteCoverMedicalExpensesSI() {
        return new Root.Quote.CoverMedicalExpensesSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverBailBondSI }
     *
     */
    public Root.Quote.CoverBailBondSI createRootQuoteCoverBailBondSI() {
        return new Root.Quote.CoverBailBondSI();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsAdjustmentFlag }
     *
     */
    public Root.Quote.PremDetailsAdjustmentFlag createRootQuotePremDetailsAdjustmentFlag() {
        return new Root.Quote.PremDetailsAdjustmentFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsReasonForAdjustment }
     *
     */
    public Root.Quote.PremDetailsReasonForAdjustment createRootQuotePremDetailsReasonForAdjustment() {
        return new Root.Quote.PremDetailsReasonForAdjustment();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsAdjustmentPct }
     *
     */
    public Root.Quote.PremDetailsAdjustmentPct createRootQuotePremDetailsAdjustmentPct() {
        return new Root.Quote.PremDetailsAdjustmentPct();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementNumber }
     *
     */
    public Root.Quote.EndorsementNumber createRootQuoteEndorsementNumber() {
        return new Root.Quote.EndorsementNumber();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementEffectiveDate }
     *
     */
    public Root.Quote.EndorsementEffectiveDate createRootQuoteEndorsementEffectiveDate() {
        return new Root.Quote.EndorsementEffectiveDate();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementType }
     *
     */
    public Root.Quote.EndorsementType createRootQuoteEndorsementType() {
        return new Root.Quote.EndorsementType();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementWithRefundOfStampDuty }
     *
     */
    public Root.Quote.EndorsementWithRefundOfStampDuty createRootQuoteEndorsementWithRefundOfStampDuty() {
        return new Root.Quote.EndorsementWithRefundOfStampDuty();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementCancellationEffectiveDate }
     *
     */
    public Root.Quote.EndorsementCancellationEffectiveDate createRootQuoteEndorsementCancellationEffectiveDate() {
        return new Root.Quote.EndorsementCancellationEffectiveDate();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementCancellationReason }
     *
     */
    public Root.Quote.EndorsementCancellationReason createRootQuoteEndorsementCancellationReason() {
        return new Root.Quote.EndorsementCancellationReason();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementCancellationRefundMethod }
     *
     */
    public Root.Quote.EndorsementCancellationRefundMethod createRootQuoteEndorsementCancellationRefundMethod() {
        return new Root.Quote.EndorsementCancellationRefundMethod();
    }

    /**
     * Create an instance of {@link Root.Quote.CarWindshieldTintPct }
     *
     */
    public Root.Quote.CarWindshieldTintPct createRootQuoteCarWindshieldTintPct() {
        return new Root.Quote.CarWindshieldTintPct();
    }

    /**
     * Create an instance of {@link Root.Quote.QuoteRef }
     *
     */
    public Root.Quote.QuoteRef createRootQuoteQuoteRef() {
        return new Root.Quote.QuoteRef();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderResidentialStatus }
     *
     */
    public Root.Quote.PolicyholderResidentialStatus createRootQuotePolicyholderResidentialStatus() {
        return new Root.Quote.PolicyholderResidentialStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderDateOfBirth }
     *
     */
    public Root.Quote.PolicyholderDateOfBirth createRootQuotePolicyholderDateOfBirth() {
        return new Root.Quote.PolicyholderDateOfBirth();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderMaritalStatus }
     *
     */
    public Root.Quote.PolicyholderMaritalStatus createRootQuotePolicyholderMaritalStatus() {
        return new Root.Quote.PolicyholderMaritalStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderGender }
     *
     */
    public Root.Quote.PolicyholderGender createRootQuotePolicyholderGender() {
        return new Root.Quote.PolicyholderGender();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderOccupation }
     *
     */
    public Root.Quote.PolicyholderOccupation createRootQuotePolicyholderOccupation() {
        return new Root.Quote.PolicyholderOccupation();
    }

    /**
     * Create an instance of {@link Root.Quote.CarUsageByOwner }
     *
     */
    public Root.Quote.CarUsageByOwner createRootQuoteCarUsageByOwner() {
        return new Root.Quote.CarUsageByOwner();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderDrivingExperience }
     *
     */
    public Root.Quote.PolicyholderDrivingExperience createRootQuotePolicyholderDrivingExperience() {
        return new Root.Quote.PolicyholderDrivingExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyholderAccidentsExperience }
     *
     */
    public Root.Quote.PolicyholderAccidentsExperience createRootQuotePolicyholderAccidentsExperience() {
        return new Root.Quote.PolicyholderAccidentsExperience();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCommercialUsageTaxi }
     *
     */
    public Root.Quote.CarCommercialUsageTaxi createRootQuoteCarCommercialUsageTaxi() {
        return new Root.Quote.CarCommercialUsageTaxi();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCommercialUsageRental }
     *
     */
    public Root.Quote.CarCommercialUsageRental createRootQuoteCarCommercialUsageRental() {
        return new Root.Quote.CarCommercialUsageRental();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCommercialUsageTransportGoods }
     *
     */
    public Root.Quote.CarCommercialUsageTransportGoods createRootQuoteCarCommercialUsageTransportGoods() {
        return new Root.Quote.CarCommercialUsageTransportGoods();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCommercialUsageTransportCompany }
     *
     */
    public Root.Quote.CarCommercialUsageTransportCompany createRootQuoteCarCommercialUsageTransportCompany() {
        return new Root.Quote.CarCommercialUsageTransportCompany();
    }

    /**
     * Create an instance of {@link Root.Quote.CarCommercialUsageTransportGoodsRoute }
     *
     */
    public Root.Quote.CarCommercialUsageTransportGoodsRoute createRootQuoteCarCommercialUsageTransportGoodsRoute() {
        return new Root.Quote.CarCommercialUsageTransportGoodsRoute();
    }

    /**
     * Create an instance of {@link Root.Quote.CarUsageType }
     *
     */
    public Root.Quote.CarUsageType createRootQuoteCarUsageType() {
        return new Root.Quote.CarUsageType();
    }

    /**
     * Create an instance of {@link Root.Quote.DiscountType }
     *
     */
    public Root.Quote.DiscountType createRootQuoteDiscountType() {
        return new Root.Quote.DiscountType();
    }

    /**
     * Create an instance of {@link Root.Quote.CarTypeCompulsoryInsuranceCode }
     *
     */
    public Root.Quote.CarTypeCompulsoryInsuranceCode createRootQuoteCarTypeCompulsoryInsuranceCode() {
        return new Root.Quote.CarTypeCompulsoryInsuranceCode();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookFamilyTableRef }
     *
     */
    public Root.Quote.RedBookFamilyTableRef createRootQuoteRedBookFamilyTableRef() {
        return new Root.Quote.RedBookFamilyTableRef();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookFamilyVehicleTypeCode }
     *
     */
    public Root.Quote.RedBookFamilyVehicleTypeCode createRootQuoteRedBookFamilyVehicleTypeCode() {
        return new Root.Quote.RedBookFamilyVehicleTypeCode();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookFamilyYearLatest }
     *
     */
    public Root.Quote.RedBookFamilyYearLatest createRootQuoteRedBookFamilyYearLatest() {
        return new Root.Quote.RedBookFamilyYearLatest();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookFamilyYearStart }
     *
     */
    public Root.Quote.RedBookFamilyYearStart createRootQuoteRedBookFamilyYearStart() {
        return new Root.Quote.RedBookFamilyYearStart();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListBodyStyleDescription }
     *
     */
    public Root.Quote.RedBookListBodyStyleDescription createRootQuoteRedBookListBodyStyleDescription() {
        return new Root.Quote.RedBookListBodyStyleDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListBuildCountryOriginDescription }
     *
     */
    public Root.Quote.RedBookListBuildCountryOriginDescription createRootQuoteRedBookListBuildCountryOriginDescription() {
        return new Root.Quote.RedBookListBuildCountryOriginDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListCylinders }
     *
     */
    public Root.Quote.RedBookListCylinders createRootQuoteRedBookListCylinders() {
        return new Root.Quote.RedBookListCylinders();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListDescription }
     *
     */
    public Root.Quote.RedBookListDescription createRootQuoteRedBookListDescription() {
        return new Root.Quote.RedBookListDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListDoorNum }
     *
     */
    public Root.Quote.RedBookListDoorNum createRootQuoteRedBookListDoorNum() {
        return new Root.Quote.RedBookListDoorNum();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListDriveDescription }
     *
     */
    public Root.Quote.RedBookListDriveDescription createRootQuoteRedBookListDriveDescription() {
        return new Root.Quote.RedBookListDriveDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListEngineDescription }
     *
     */
    public Root.Quote.RedBookListEngineDescription createRootQuoteRedBookListEngineDescription() {
        return new Root.Quote.RedBookListEngineDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListEngineSize }
     *
     */
    public Root.Quote.RedBookListEngineSize createRootQuoteRedBookListEngineSize() {
        return new Root.Quote.RedBookListEngineSize();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListExtraIdentification }
     *
     */
    public Root.Quote.RedBookListExtraIdentification createRootQuoteRedBookListExtraIdentification() {
        return new Root.Quote.RedBookListExtraIdentification();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListFuelTypeDescription }
     *
     */
    public Root.Quote.RedBookListFuelTypeDescription createRootQuoteRedBookListFuelTypeDescription() {
        return new Root.Quote.RedBookListFuelTypeDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListGearLocationDescription }
     *
     */
    public Root.Quote.RedBookListGearLocationDescription createRootQuoteRedBookListGearLocationDescription() {
        return new Root.Quote.RedBookListGearLocationDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListGearNum }
     *
     */
    public Root.Quote.RedBookListGearNum createRootQuoteRedBookListGearNum() {
        return new Root.Quote.RedBookListGearNum();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListGearTypeDescription }
     *
     */
    public Root.Quote.RedBookListGearTypeDescription createRootQuoteRedBookListGearTypeDescription() {
        return new Root.Quote.RedBookListGearTypeDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListGoodKM }
     *
     */
    public Root.Quote.RedBookListGoodKM createRootQuoteRedBookListGoodKM() {
        return new Root.Quote.RedBookListGoodKM();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListImportStatus }
     *
     */
    public Root.Quote.RedBookListImportStatus createRootQuoteRedBookListImportStatus() {
        return new Root.Quote.RedBookListImportStatus();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListInductionDescription }
     *
     */
    public Root.Quote.RedBookListInductionDescription createRootQuoteRedBookListInductionDescription() {
        return new Root.Quote.RedBookListInductionDescription();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListLimitedEdition }
     *
     */
    public Root.Quote.RedBookListLimitedEdition createRootQuoteRedBookListLimitedEdition() {
        return new Root.Quote.RedBookListLimitedEdition();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListMaximumSpeed }
     *
     */
    public Root.Quote.RedBookListMaximumSpeed createRootQuoteRedBookListMaximumSpeed() {
        return new Root.Quote.RedBookListMaximumSpeed();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListMonthGroup }
     *
     */
    public Root.Quote.RedBookListMonthGroup createRootQuoteRedBookListMonthGroup() {
        return new Root.Quote.RedBookListMonthGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListSeatCapacity }
     *
     */
    public Root.Quote.RedBookListSeatCapacity createRootQuoteRedBookListSeatCapacity() {
        return new Root.Quote.RedBookListSeatCapacity();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListSequenceNum }
     *
     */
    public Root.Quote.RedBookListSequenceNum createRootQuoteRedBookListSequenceNum() {
        return new Root.Quote.RedBookListSequenceNum();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListSeries }
     *
     */
    public Root.Quote.RedBookListSeries createRootQuoteRedBookListSeries() {
        return new Root.Quote.RedBookListSeries();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListTableRef }
     *
     */
    public Root.Quote.RedBookListTableRef createRootQuoteRedBookListTableRef() {
        return new Root.Quote.RedBookListTableRef();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListValueAvgRetail }
     *
     */
    public Root.Quote.RedBookListValueAvgRetail createRootQuoteRedBookListValueAvgRetail() {
        return new Root.Quote.RedBookListValueAvgRetail();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListValueAvgWholesale }
     *
     */
    public Root.Quote.RedBookListValueAvgWholesale createRootQuoteRedBookListValueAvgWholesale() {
        return new Root.Quote.RedBookListValueAvgWholesale();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListValueGoodRetail }
     *
     */
    public Root.Quote.RedBookListValueGoodRetail createRootQuoteRedBookListValueGoodRetail() {
        return new Root.Quote.RedBookListValueGoodRetail();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListValueGoodWholesale }
     *
     */
    public Root.Quote.RedBookListValueGoodWholesale createRootQuoteRedBookListValueGoodWholesale() {
        return new Root.Quote.RedBookListValueGoodWholesale();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListValueNewPrice }
     *
     */
    public Root.Quote.RedBookListValueNewPrice createRootQuoteRedBookListValueNewPrice() {
        return new Root.Quote.RedBookListValueNewPrice();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListVehicleTypeCode }
     *
     */
    public Root.Quote.RedBookListVehicleTypeCode createRootQuoteRedBookListVehicleTypeCode() {
        return new Root.Quote.RedBookListVehicleTypeCode();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListYearGroup }
     *
     */
    public Root.Quote.RedBookListYearGroup createRootQuoteRedBookListYearGroup() {
        return new Root.Quote.RedBookListYearGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.UWClass }
     *
     */
    public Root.Quote.UWClass createRootQuoteUWClass() {
        return new Root.Quote.UWClass();
    }

    /**
     * Create an instance of {@link Root.Quote.UWGroup }
     *
     */
    public Root.Quote.UWGroup createRootQuoteUWGroup() {
        return new Root.Quote.UWGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.UWPremiumClass }
     *
     */
    public Root.Quote.UWPremiumClass createRootQuoteUWPremiumClass() {
        return new Root.Quote.UWPremiumClass();
    }

    /**
     * Create an instance of {@link Root.Quote.UWPremiumGroup }
     *
     */
    public Root.Quote.UWPremiumGroup createRootQuoteUWPremiumGroup() {
        return new Root.Quote.UWPremiumGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.UWTariffGroup }
     *
     */
    public Root.Quote.UWTariffGroup createRootQuoteUWTariffGroup() {
        return new Root.Quote.UWTariffGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleType }
     *
     */
    public Root.Quote.UWVehicleType createRootQuoteUWVehicleType() {
        return new Root.Quote.UWVehicleType();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryRimsTyres }
     *
     */
    public Root.Quote.CarAccessoryRimsTyres createRootQuoteCarAccessoryRimsTyres() {
        return new Root.Quote.CarAccessoryRimsTyres();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryRimsTyresValue }
     *
     */
    public Root.Quote.CarAccessoryRimsTyresValue createRootQuoteCarAccessoryRimsTyresValue() {
        return new Root.Quote.CarAccessoryRimsTyresValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessorySolarFilm }
     *
     */
    public Root.Quote.CarAccessorySolarFilm createRootQuoteCarAccessorySolarFilm() {
        return new Root.Quote.CarAccessorySolarFilm();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessorySolarFilmValue }
     *
     */
    public Root.Quote.CarAccessorySolarFilmValue createRootQuoteCarAccessorySolarFilmValue() {
        return new Root.Quote.CarAccessorySolarFilmValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryInCarEntertainment }
     *
     */
    public Root.Quote.CarAccessoryInCarEntertainment createRootQuoteCarAccessoryInCarEntertainment() {
        return new Root.Quote.CarAccessoryInCarEntertainment();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryInCarEntertainmentValue }
     *
     */
    public Root.Quote.CarAccessoryInCarEntertainmentValue createRootQuoteCarAccessoryInCarEntertainmentValue() {
        return new Root.Quote.CarAccessoryInCarEntertainmentValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessorySuspensionStabiliser }
     *
     */
    public Root.Quote.CarAccessorySuspensionStabiliser createRootQuoteCarAccessorySuspensionStabiliser() {
        return new Root.Quote.CarAccessorySuspensionStabiliser();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessorySuspensionStabiliserValue }
     *
     */
    public Root.Quote.CarAccessorySuspensionStabiliserValue createRootQuoteCarAccessorySuspensionStabiliserValue() {
        return new Root.Quote.CarAccessorySuspensionStabiliserValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryAirIntakeExhaust }
     *
     */
    public Root.Quote.CarAccessoryAirIntakeExhaust createRootQuoteCarAccessoryAirIntakeExhaust() {
        return new Root.Quote.CarAccessoryAirIntakeExhaust();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryAirIntakeExhaustValue }
     *
     */
    public Root.Quote.CarAccessoryAirIntakeExhaustValue createRootQuoteCarAccessoryAirIntakeExhaustValue() {
        return new Root.Quote.CarAccessoryAirIntakeExhaustValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryCarCamera }
     *
     */
    public Root.Quote.CarAccessoryCarCamera createRootQuoteCarAccessoryCarCamera() {
        return new Root.Quote.CarAccessoryCarCamera();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryCarCameraValue }
     *
     */
    public Root.Quote.CarAccessoryCarCameraValue createRootQuoteCarAccessoryCarCameraValue() {
        return new Root.Quote.CarAccessoryCarCameraValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryRearCamera }
     *
     */
    public Root.Quote.CarAccessoryRearCamera createRootQuoteCarAccessoryRearCamera() {
        return new Root.Quote.CarAccessoryRearCamera();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryRearCameraValue }
     *
     */
    public Root.Quote.CarAccessoryRearCameraValue createRootQuoteCarAccessoryRearCameraValue() {
        return new Root.Quote.CarAccessoryRearCameraValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryBodyKit }
     *
     */
    public Root.Quote.CarAccessoryBodyKit createRootQuoteCarAccessoryBodyKit() {
        return new Root.Quote.CarAccessoryBodyKit();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryBodyKitValue }
     *
     */
    public Root.Quote.CarAccessoryBodyKitValue createRootQuoteCarAccessoryBodyKitValue() {
        return new Root.Quote.CarAccessoryBodyKitValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryCarryBoy }
     *
     */
    public Root.Quote.CarAccessoryCarryBoy createRootQuoteCarAccessoryCarryBoy() {
        return new Root.Quote.CarAccessoryCarryBoy();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryCarryBoyValue }
     *
     */
    public Root.Quote.CarAccessoryCarryBoyValue createRootQuoteCarAccessoryCarryBoyValue() {
        return new Root.Quote.CarAccessoryCarryBoyValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryGasFuelingSystem }
     *
     */
    public Root.Quote.CarAccessoryGasFuelingSystem createRootQuoteCarAccessoryGasFuelingSystem() {
        return new Root.Quote.CarAccessoryGasFuelingSystem();
    }

    /**
     * Create an instance of {@link Root.Quote.CarAccessoryGasFuelingSystemValue }
     *
     */
    public Root.Quote.CarAccessoryGasFuelingSystemValue createRootQuoteCarAccessoryGasFuelingSystemValue() {
        return new Root.Quote.CarAccessoryGasFuelingSystemValue();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDManufacturer }
     *
     */
    public Root.Quote.CarATDManufacturer createRootQuoteCarATDManufacturer() {
        return new Root.Quote.CarATDManufacturer();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDManufacturerPlusExtra }
     *
     */
    public Root.Quote.CarATDManufacturerPlusExtra createRootQuoteCarATDManufacturerPlusExtra() {
        return new Root.Quote.CarATDManufacturerPlusExtra();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDSteeringWheelLock }
     *
     */
    public Root.Quote.CarATDSteeringWheelLock createRootQuoteCarATDSteeringWheelLock() {
        return new Root.Quote.CarATDSteeringWheelLock();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDKillSwitch }
     *
     */
    public Root.Quote.CarATDKillSwitch createRootQuoteCarATDKillSwitch() {
        return new Root.Quote.CarATDKillSwitch();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDAlarm }
     *
     */
    public Root.Quote.CarATDAlarm createRootQuoteCarATDAlarm() {
        return new Root.Quote.CarATDAlarm();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDTyreLocks }
     *
     */
    public Root.Quote.CarATDTyreLocks createRootQuoteCarATDTyreLocks() {
        return new Root.Quote.CarATDTyreLocks();
    }

    /**
     * Create an instance of {@link Root.Quote.CarATDTracker }
     *
     */
    public Root.Quote.CarATDTracker createRootQuoteCarATDTracker() {
        return new Root.Quote.CarATDTracker();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1OccupationGroup }
     *
     */
    public Root.Quote.Driver1OccupationGroup createRootQuoteDriver1OccupationGroup() {
        return new Root.Quote.Driver1OccupationGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2OccupationGroup }
     *
     */
    public Root.Quote.Driver2OccupationGroup createRootQuoteDriver2OccupationGroup() {
        return new Root.Quote.Driver2OccupationGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3OccupationGroup }
     *
     */
    public Root.Quote.Driver3OccupationGroup createRootQuoteDriver3OccupationGroup() {
        return new Root.Quote.Driver3OccupationGroup();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverVariableExcessLevel }
     *
     */
    public Root.Quote.CoverVariableExcessLevel createRootQuoteCoverVariableExcessLevel() {
        return new Root.Quote.CoverVariableExcessLevel();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1IsPresent }
     *
     */
    public Root.Quote.Driver1IsPresent createRootQuoteDriver1IsPresent() {
        return new Root.Quote.Driver1IsPresent();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2IsPresent }
     *
     */
    public Root.Quote.Driver2IsPresent createRootQuoteDriver2IsPresent() {
        return new Root.Quote.Driver2IsPresent();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3IsPresent }
     *
     */
    public Root.Quote.Driver3IsPresent createRootQuoteDriver3IsPresent() {
        return new Root.Quote.Driver3IsPresent();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4IsPresent }
     *
     */
    public Root.Quote.Driver4IsPresent createRootQuoteDriver4IsPresent() {
        return new Root.Quote.Driver4IsPresent();
    }

    /**
     * Create an instance of {@link Root.Quote.RadarCallType }
     *
     */
    public Root.Quote.RadarCallType createRootQuoteRadarCallType() {
        return new Root.Quote.RadarCallType();
    }

    /**
     * Create an instance of {@link Root.Quote.QuoteDateOfFirstNBQuote }
     *
     */
    public Root.Quote.QuoteDateOfFirstNBQuote createRootQuoteQuoteDateOfFirstNBQuote() {
        return new Root.Quote.QuoteDateOfFirstNBQuote();
    }

    /**
     * Create an instance of {@link Root.Quote.QuoteChannelFirstContact }
     *
     */
    public Root.Quote.QuoteChannelFirstContact createRootQuoteQuoteChannelFirstContact() {
        return new Root.Quote.QuoteChannelFirstContact();
    }

    /**
     * Create an instance of {@link Root.Quote.QuoteDateOfQuote }
     *
     */
    public Root.Quote.QuoteDateOfQuote createRootQuoteQuoteDateOfQuote() {
        return new Root.Quote.QuoteDateOfQuote();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookVersionNumber }
     *
     */
    public Root.Quote.RedBookVersionNumber createRootQuoteRedBookVersionNumber() {
        return new Root.Quote.RedBookVersionNumber();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyChannelPayment }
     *
     */
    public Root.Quote.PolicyChannelPayment createRootQuotePolicyChannelPayment() {
        return new Root.Quote.PolicyChannelPayment();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1DOB }
     *
     */
    public Root.Quote.Driver1DOB createRootQuoteDriver1DOB() {
        return new Root.Quote.Driver1DOB();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2DOB }
     *
     */
    public Root.Quote.Driver2DOB createRootQuoteDriver2DOB() {
        return new Root.Quote.Driver2DOB();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3DOB }
     *
     */
    public Root.Quote.Driver3DOB createRootQuoteDriver3DOB() {
        return new Root.Quote.Driver3DOB();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4DOB }
     *
     */
    public Root.Quote.Driver4DOB createRootQuoteDriver4DOB() {
        return new Root.Quote.Driver4DOB();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyDeclarationAnswer }
     *
     */
    public Root.Quote.PolicyDeclarationAnswer createRootQuotePolicyDeclarationAnswer() {
        return new Root.Quote.PolicyDeclarationAnswer();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyRenewalInviteCount }
     *
     */
    public Root.Quote.PolicyRenewalInviteCount createRootQuotePolicyRenewalInviteCount() {
        return new Root.Quote.PolicyRenewalInviteCount();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1IsOwner }
     *
     */
    public Root.Quote.Driver1IsOwner createRootQuoteDriver1IsOwner() {
        return new Root.Quote.Driver1IsOwner();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2IsOwner }
     *
     */
    public Root.Quote.Driver2IsOwner createRootQuoteDriver2IsOwner() {
        return new Root.Quote.Driver2IsOwner();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3IsOwner }
     *
     */
    public Root.Quote.Driver3IsOwner createRootQuoteDriver3IsOwner() {
        return new Root.Quote.Driver3IsOwner();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4IsOwner }
     *
     */
    public Root.Quote.Driver4IsOwner createRootQuoteDriver4IsOwner() {
        return new Root.Quote.Driver4IsOwner();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementCarChangeFlag }
     *
     */
    public Root.Quote.EndorsementCarChangeFlag createRootQuoteEndorsementCarChangeFlag() {
        return new Root.Quote.EndorsementCarChangeFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementNCBChangeFlag }
     *
     */
    public Root.Quote.EndorsementNCBChangeFlag createRootQuoteEndorsementNCBChangeFlag() {
        return new Root.Quote.EndorsementNCBChangeFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementAddressChangeFlag }
     *
     */
    public Root.Quote.EndorsementAddressChangeFlag createRootQuoteEndorsementAddressChangeFlag() {
        return new Root.Quote.EndorsementAddressChangeFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementPHChangeFlag }
     *
     */
    public Root.Quote.EndorsementPHChangeFlag createRootQuoteEndorsementPHChangeFlag() {
        return new Root.Quote.EndorsementPHChangeFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.EndorsementCoverTypeChangeFlag }
     *
     */
    public Root.Quote.EndorsementCoverTypeChangeFlag createRootQuoteEndorsementCoverTypeChangeFlag() {
        return new Root.Quote.EndorsementCoverTypeChangeFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver1RelationToPH }
     *
     */
    public Root.Quote.Driver1RelationToPH createRootQuoteDriver1RelationToPH() {
        return new Root.Quote.Driver1RelationToPH();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver2RelationToPH }
     *
     */
    public Root.Quote.Driver2RelationToPH createRootQuoteDriver2RelationToPH() {
        return new Root.Quote.Driver2RelationToPH();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver3RelationToPH }
     *
     */
    public Root.Quote.Driver3RelationToPH createRootQuoteDriver3RelationToPH() {
        return new Root.Quote.Driver3RelationToPH();
    }

    /**
     * Create an instance of {@link Root.Quote.Driver4RelationToPH }
     *
     */
    public Root.Quote.Driver4RelationToPH createRootQuoteDriver4RelationToPH() {
        return new Root.Quote.Driver4RelationToPH();
    }

    /**
     * Create an instance of {@link Root.Quote.TentativeStartDate }
     *
     */
    public Root.Quote.TentativeStartDate createRootQuoteTentativeStartDate() {
        return new Root.Quote.TentativeStartDate();
    }

    /**
     * Create an instance of {@link Root.Quote.ProductType }
     *
     */
    public Root.Quote.ProductType createRootQuoteProductType() {
        return new Root.Quote.ProductType();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListKerbWeight }
     *
     */
    public Root.Quote.RedBookListKerbWeight createRootQuoteRedBookListKerbWeight() {
        return new Root.Quote.RedBookListKerbWeight();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListPower }
     *
     */
    public Root.Quote.RedBookListPower createRootQuoteRedBookListPower() {
        return new Root.Quote.RedBookListPower();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListSeatHeight }
     *
     */
    public Root.Quote.RedBookListSeatHeight createRootQuoteRedBookListSeatHeight() {
        return new Root.Quote.RedBookListSeatHeight();
    }

    /**
     * Create an instance of {@link Root.Quote.NonAnnualPaymentLoadingFactor }
     *
     */
    public Root.Quote.NonAnnualPaymentLoadingFactor createRootQuoteNonAnnualPaymentLoadingFactor() {
        return new Root.Quote.NonAnnualPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsRenewalAdjustmentPct }
     *
     */
    public Root.Quote.PremDetailsRenewalAdjustmentPct createRootQuotePremDetailsRenewalAdjustmentPct() {
        return new Root.Quote.PremDetailsRenewalAdjustmentPct();
    }

    /**
     * Create an instance of {@link Root.Quote.RedBookListFamilyCode }
     *
     */
    public Root.Quote.RedBookListFamilyCode createRootQuoteRedBookListFamilyCode() {
        return new Root.Quote.RedBookListFamilyCode();
    }

    /**
     * Create an instance of {@link Root.Quote.GeoPostalCode }
     *
     */
    public Root.Quote.GeoPostalCode createRootQuoteGeoPostalCode() {
        return new Root.Quote.GeoPostalCode();
    }

    /**
     * Create an instance of {@link Root.Quote.CarPlateNumber }
     *
     */
    public Root.Quote.CarPlateNumber createRootQuoteCarPlateNumber() {
        return new Root.Quote.CarPlateNumber();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleTypeUpdateFlag }
     *
     */
    public Root.Quote.UWVehicleTypeUpdateFlag createRootQuoteUWVehicleTypeUpdateFlag() {
        return new Root.Quote.UWVehicleTypeUpdateFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleTypeRedbook }
     *
     */
    public Root.Quote.UWVehicleTypeRedbook createRootQuoteUWVehicleTypeRedbook() {
        return new Root.Quote.UWVehicleTypeRedbook();
    }

    /**
     * Create an instance of {@link Root.Quote.CarTypeCompulsoryInsuranceCodeRedbook }
     *
     */
    public Root.Quote.CarTypeCompulsoryInsuranceCodeRedbook createRootQuoteCarTypeCompulsoryInsuranceCodeRedbook() {
        return new Root.Quote.CarTypeCompulsoryInsuranceCodeRedbook();
    }

}
