
package com.roojai.radar.stubMotor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConfigurationFaultContract", targetNamespace = "http://towerswatson.com/rto/dpo/types/2010/01")
public class DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConfigurationFaultContract faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message, ConfigurationFaultContract faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message, ConfigurationFaultContract faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.roojai.ConfigurationFaultContract
     */
    public ConfigurationFaultContract getFaultInfo() {
        return faultInfo;
    }

}
