//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 03:33:10 PM ICT 
//


package com.roojai.radar.stubMotor.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     *
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Quote }
     *
     */
    public Root.Quote createRootQuote() {
        return new Root.Quote();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIDefaultSI }
     *
     */
    public Root.Quote.AddBenefitsTPBIDefaultSI createRootQuoteAddBenefitsTPBIDefaultSI() {
        return new Root.Quote.AddBenefitsTPBIDefaultSI();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType2 createRootQuoteArrayPrem0XsAnyWorkshopNamedCompType2() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType3 createRootQuoteArrayPrem0XsAnyWorkshopNamedCompType3() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType2 createRootQuoteArrayPrem0XsAnyWorkshopNamedNoCompType2() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType3 createRootQuoteArrayPrem0XsAnyWorkshopNamedNoCompType3() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem20000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem20000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem20000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem20000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem20000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem20000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem20000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem20000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem20000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem20000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem20000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem20000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem20000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem20000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem20000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem20000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem30000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem30000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem30000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem30000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem30000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem30000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem30000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem30000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem30000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem30000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem30000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem30000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem30000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem30000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem30000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem30000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem40000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem40000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem40000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem40000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem40000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem40000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem40000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem40000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem40000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem40000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem40000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem40000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem40000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem40000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem40000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem40000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem50000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem50000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem50000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem50000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem50000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem50000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem50000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem50000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem50000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem50000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem50000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem50000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem50000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem50000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem50000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem50000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesDataValidation }
     *
     */
    public Root.Quote.BusinessRulesDataValidation createRootQuoteBusinessRulesDataValidation() {
        return new Root.Quote.BusinessRulesDataValidation();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesErrorMessages }
     *
     */
    public Root.Quote.BusinessRulesErrorMessages createRootQuoteBusinessRulesErrorMessages() {
        return new Root.Quote.BusinessRulesErrorMessages();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesMaxAuthorisationLevel }
     *
     */
    public Root.Quote.BusinessRulesMaxAuthorisationLevel createRootQuoteBusinessRulesMaxAuthorisationLevel() {
        return new Root.Quote.BusinessRulesMaxAuthorisationLevel();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesResult }
     *
     */
    public Root.Quote.BusinessRulesResult createRootQuoteBusinessRulesResult() {
        return new Root.Quote.BusinessRulesResult();
    }

    /**
     * Create an instance of {@link Root.Quote.CarDefaultValueFinal }
     *
     */
    public Root.Quote.CarDefaultValueFinal createRootQuoteCarDefaultValueFinal() {
        return new Root.Quote.CarDefaultValueFinal();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverBailBondSI }
     *
     */
    public Root.Quote.CoverBailBondSI createRootQuoteCoverBailBondSI() {
        return new Root.Quote.CoverBailBondSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverDriverPlan }
     *
     */
    public Root.Quote.CoverDriverPlan createRootQuoteCoverDriverPlan() {
        return new Root.Quote.CoverDriverPlan();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverIncludesCompulsoryFlag }
     *
     */
    public Root.Quote.CoverIncludesCompulsoryFlag createRootQuoteCoverIncludesCompulsoryFlag() {
        return new Root.Quote.CoverIncludesCompulsoryFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverMedicalExpensesSI }
     *
     */
    public Root.Quote.CoverMedicalExpensesSI createRootQuoteCoverMedicalExpensesSI() {
        return new Root.Quote.CoverMedicalExpensesSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODCollisionSI }
     *
     */
    public Root.Quote.CoverODCollisionSI createRootQuoteCoverODCollisionSI() {
        return new Root.Quote.CoverODCollisionSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODDeductibleAmount }
     *
     */
    public Root.Quote.CoverODDeductibleAmount createRootQuoteCoverODDeductibleAmount() {
        return new Root.Quote.CoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODFireTheftSI }
     *
     */
    public Root.Quote.CoverODFireTheftSI createRootQuoteCoverODFireTheftSI() {
        return new Root.Quote.CoverODFireTheftSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODNaturalDisasterSI }
     *
     */
    public Root.Quote.CoverODNaturalDisasterSI createRootQuoteCoverODNaturalDisasterSI() {
        return new Root.Quote.CoverODNaturalDisasterSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODPersonalAccidentSI }
     *
     */
    public Root.Quote.CoverODPersonalAccidentSI createRootQuoteCoverODPersonalAccidentSI() {
        return new Root.Quote.CoverODPersonalAccidentSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPADriversSI }
     *
     */
    public Root.Quote.CoverPADriversSI createRootQuoteCoverPADriversSI() {
        return new Root.Quote.CoverPADriversSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPAPassengersSI }
     *
     */
    public Root.Quote.CoverPAPassengersSI createRootQuoteCoverPAPassengersSI() {
        return new Root.Quote.CoverPAPassengersSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryBodilyInjuryAccidentSI }
     *
     */
    public Root.Quote.CoverTPVoluntaryBodilyInjuryAccidentSI createRootQuoteCoverTPVoluntaryBodilyInjuryAccidentSI() {
        return new Root.Quote.CoverTPVoluntaryBodilyInjuryAccidentSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryBodilyInjurySI }
     *
     */
    public Root.Quote.CoverTPVoluntaryBodilyInjurySI createRootQuoteCoverTPVoluntaryBodilyInjurySI() {
        return new Root.Quote.CoverTPVoluntaryBodilyInjurySI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryPropertyDamageSI }
     *
     */
    public Root.Quote.CoverTPVoluntaryPropertyDamageSI createRootQuoteCoverTPVoluntaryPropertyDamageSI() {
        return new Root.Quote.CoverTPVoluntaryPropertyDamageSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTerritorialSelection }
     *
     */
    public Root.Quote.CoverTerritorialSelection createRootQuoteCoverTerritorialSelection() {
        return new Root.Quote.CoverTerritorialSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverVoluntaryType }
     *
     */
    public Root.Quote.CoverVoluntaryType createRootQuoteCoverVoluntaryType() {
        return new Root.Quote.CoverVoluntaryType();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverWindscreenSI }
     *
     */
    public Root.Quote.CoverWindscreenSI createRootQuoteCoverWindscreenSI() {
        return new Root.Quote.CoverWindscreenSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverWorkshopSelection }
     *
     */
    public Root.Quote.CoverWorkshopSelection createRootQuoteCoverWorkshopSelection() {
        return new Root.Quote.CoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CurrentCode }
     *
     */
    public Root.Quote.CurrentCode createRootQuoteCurrentCode() {
        return new Root.Quote.CurrentCode();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverDriverPlan }
     *
     */
    public Root.Quote.DefaultCoverDriverPlan createRootQuoteDefaultCoverDriverPlan() {
        return new Root.Quote.DefaultCoverDriverPlan();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverIncludesCompulsoryFlag }
     *
     */
    public Root.Quote.DefaultCoverIncludesCompulsoryFlag createRootQuoteDefaultCoverIncludesCompulsoryFlag() {
        return new Root.Quote.DefaultCoverIncludesCompulsoryFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverODDeductibleAmount }
     *
     */
    public Root.Quote.DefaultCoverODDeductibleAmount createRootQuoteDefaultCoverODDeductibleAmount() {
        return new Root.Quote.DefaultCoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverVoluntaryType }
     *
     */
    public Root.Quote.DefaultCoverVoluntaryType createRootQuoteDefaultCoverVoluntaryType() {
        return new Root.Quote.DefaultCoverVoluntaryType();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverWorkshopSelection }
     *
     */
    public Root.Quote.DefaultCoverWorkshopSelection createRootQuoteDefaultCoverWorkshopSelection() {
        return new Root.Quote.DefaultCoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultPremiumVoluntaryBeforeTaxes }
     *
     */
    public Root.Quote.DefaultPremiumVoluntaryBeforeTaxes createRootQuoteDefaultPremiumVoluntaryBeforeTaxes() {
        return new Root.Quote.DefaultPremiumVoluntaryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.FaultClaimsForRating }
     *
     */
    public Root.Quote.FaultClaimsForRating createRootQuoteFaultClaimsForRating() {
        return new Root.Quote.FaultClaimsForRating();
    }

    /**
     * Create an instance of {@link Root.Quote.MonthlyNoDepositPaymentLoadingFactor }
     *
     */
    public Root.Quote.MonthlyNoDepositPaymentLoadingFactor createRootQuoteMonthlyNoDepositPaymentLoadingFactor() {
        return new Root.Quote.MonthlyNoDepositPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.NonAnnualPaymentLoadingFactor }
     *
     */
    public Root.Quote.NonAnnualPaymentLoadingFactor createRootQuoteNonAnnualPaymentLoadingFactor() {
        return new Root.Quote.NonAnnualPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyProductVersion }
     *
     */
    public Root.Quote.PolicyProductVersion createRootQuotePolicyProductVersion() {
        return new Root.Quote.PolicyProductVersion();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsCalculatedNCBPct }
     *
     */
    public Root.Quote.PremDetailsCalculatedNCBPct createRootQuotePremDetailsCalculatedNCBPct() {
        return new Root.Quote.PremDetailsCalculatedNCBPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsRenewalAdjustmentPct }
     *
     */
    public Root.Quote.PremDetailsRenewalAdjustmentPct createRootQuotePremDetailsRenewalAdjustmentPct() {
        return new Root.Quote.PremDetailsRenewalAdjustmentPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTariffMaximum }
     *
     */
    public Root.Quote.PremDetailsTariffMaximum createRootQuotePremDetailsTariffMaximum() {
        return new Root.Quote.PremDetailsTariffMaximum();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTariffMinimum }
     *
     */
    public Root.Quote.PremDetailsTariffMinimum createRootQuotePremDetailsTariffMinimum() {
        return new Root.Quote.PremDetailsTariffMinimum();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTechnicalAdjusted }
     *
     */
    public Root.Quote.PremDetailsTechnicalAdjusted createRootQuotePremDetailsTechnicalAdjusted() {
        return new Root.Quote.PremDetailsTechnicalAdjusted();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTechnicalAuto }
     *
     */
    public Root.Quote.PremDetailsTechnicalAuto createRootQuotePremDetailsTechnicalAuto() {
        return new Root.Quote.PremDetailsTechnicalAuto();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsVoluntaryDiscountPct }
     *
     */
    public Root.Quote.PremDetailsVoluntaryDiscountPct createRootQuotePremDetailsVoluntaryDiscountPct() {
        return new Root.Quote.PremDetailsVoluntaryDiscountPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBailBond }
     *
     */
    public Root.Quote.PremFinalBailBond createRootQuotePremFinalBailBond() {
        return new Root.Quote.PremFinalBailBond();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBasic123 }
     *
     */
    public Root.Quote.PremFinalBasic123 createRootQuotePremFinalBasic123() {
        return new Root.Quote.PremFinalBasic123();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBasic5 }
     *
     */
    public Root.Quote.PremFinalBasic5 createRootQuotePremFinalBasic5() {
        return new Root.Quote.PremFinalBasic5();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCompulsoryBeforeTaxes }
     *
     */
    public Root.Quote.PremFinalCompulsoryBeforeTaxes createRootQuotePremFinalCompulsoryBeforeTaxes() {
        return new Root.Quote.PremFinalCompulsoryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCompulsoryCommission }
     *
     */
    public Root.Quote.PremFinalCompulsoryCommission createRootQuotePremFinalCompulsoryCommission() {
        return new Root.Quote.PremFinalCompulsoryCommission();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCore123 }
     *
     */
    public Root.Quote.PremFinalCore123 createRootQuotePremFinalCore123() {
        return new Root.Quote.PremFinalCore123();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCore5 }
     *
     */
    public Root.Quote.PremFinalCore5 createRootQuotePremFinalCore5() {
        return new Root.Quote.PremFinalCore5();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalLoadingFactor123 }
     *
     */
    public Root.Quote.PremFinalLoadingFactor123 createRootQuotePremFinalLoadingFactor123() {
        return new Root.Quote.PremFinalLoadingFactor123();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalLoadingFactor5 }
     *
     */
    public Root.Quote.PremFinalLoadingFactor5 createRootQuotePremFinalLoadingFactor5() {
        return new Root.Quote.PremFinalLoadingFactor5();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalMedicalExpenses }
     *
     */
    public Root.Quote.PremFinalMedicalExpenses createRootQuotePremFinalMedicalExpenses() {
        return new Root.Quote.PremFinalMedicalExpenses();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalNCB }
     *
     */
    public Root.Quote.PremFinalNCB createRootQuotePremFinalNCB() {
        return new Root.Quote.PremFinalNCB();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalNamedDriverDiscount }
     *
     */
    public Root.Quote.PremFinalNamedDriverDiscount createRootQuotePremFinalNamedDriverDiscount() {
        return new Root.Quote.PremFinalNamedDriverDiscount();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalODDeductible }
     *
     */
    public Root.Quote.PremFinalODDeductible createRootQuotePremFinalODDeductible() {
        return new Root.Quote.PremFinalODDeductible();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalPADrivers }
     *
     */
    public Root.Quote.PremFinalPADrivers createRootQuotePremFinalPADrivers() {
        return new Root.Quote.PremFinalPADrivers();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalPAPassengers }
     *
     */
    public Root.Quote.PremFinalPAPassengers createRootQuotePremFinalPAPassengers() {
        return new Root.Quote.PremFinalPAPassengers();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryBasic }
     *
     */
    public Root.Quote.PremFinalVoluntaryBasic createRootQuotePremFinalVoluntaryBasic() {
        return new Root.Quote.PremFinalVoluntaryBasic();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryBeforeTaxes }
     *
     */
    public Root.Quote.PremFinalVoluntaryBeforeTaxes createRootQuotePremFinalVoluntaryBeforeTaxes() {
        return new Root.Quote.PremFinalVoluntaryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryCommission }
     *
     */
    public Root.Quote.PremFinalVoluntaryCommission createRootQuotePremFinalVoluntaryCommission() {
        return new Root.Quote.PremFinalVoluntaryCommission();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryDiscount }
     *
     */
    public Root.Quote.PremFinalVoluntaryDiscount createRootQuotePremFinalVoluntaryDiscount() {
        return new Root.Quote.PremFinalVoluntaryDiscount();
    }

    /**
     * Create an instance of {@link Root.Quote.QuarterlyPaymentLoadingFactor }
     *
     */
    public Root.Quote.QuarterlyPaymentLoadingFactor createRootQuoteQuarterlyPaymentLoadingFactor() {
        return new Root.Quote.QuarterlyPaymentLoadingFactor();
    }

}
