
package com.roojai.radar.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-07T15:46:03.521+07:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "ConfigurationFaultContract", targetNamespace = "http://towerswatson.com/rto/dpo/types/2010/01")
public class DpoServiceGetPofConfigurationFaultContractFaultFaultMessage extends Exception {
    
    private com.roojai.radar.stub.ConfigurationFaultContract configurationFaultContract;

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage() {
        super();
    }
    
    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message) {
        super(message);
    }
    
    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, com.roojai.radar.stub.ConfigurationFaultContract configurationFaultContract) {
        super(message);
        this.configurationFaultContract = configurationFaultContract;
    }

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, com.roojai.radar.stub.ConfigurationFaultContract configurationFaultContract, Throwable cause) {
        super(message, cause);
        this.configurationFaultContract = configurationFaultContract;
    }

    public com.roojai.radar.stub.ConfigurationFaultContract getFaultInfo() {
        return this.configurationFaultContract;
    }
}
