//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 10:27:01 AM ICT 
//


package com.roojai.radar.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     *
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Quote }
     *
     */
    public Root.Quote createRootQuote() {
        return new Root.Quote();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsPAMEDefaultSI }
     *
     */
    public Root.Quote.AddBenefitsPAMEDefaultSI createRootQuoteAddBenefitsPAMEDefaultSI() {
        return new Root.Quote.AddBenefitsPAMEDefaultSI();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsPAMEPremSI100K }
     *
     */
    public Root.Quote.AddBenefitsPAMEPremSI100K createRootQuoteAddBenefitsPAMEPremSI100K() {
        return new Root.Quote.AddBenefitsPAMEPremSI100K();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsPAMEPremSI1M }
     *
     */
    public Root.Quote.AddBenefitsPAMEPremSI1M createRootQuoteAddBenefitsPAMEPremSI1M() {
        return new Root.Quote.AddBenefitsPAMEPremSI1M();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsPAMEPremSI200K }
     *
     */
    public Root.Quote.AddBenefitsPAMEPremSI200K createRootQuoteAddBenefitsPAMEPremSI200K() {
        return new Root.Quote.AddBenefitsPAMEPremSI200K();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsPAMEPremSI500K }
     *
     */
    public Root.Quote.AddBenefitsPAMEPremSI500K createRootQuoteAddBenefitsPAMEPremSI500K() {
        return new Root.Quote.AddBenefitsPAMEPremSI500K();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIDefaultSI }
     *
     */
    public Root.Quote.AddBenefitsTPBIDefaultSI createRootQuoteAddBenefitsTPBIDefaultSI() {
        return new Root.Quote.AddBenefitsTPBIDefaultSI();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIPremSI500K }
     *
     */
    public Root.Quote.AddBenefitsTPBIPremSI500K createRootQuoteAddBenefitsTPBIPremSI500K() {
        return new Root.Quote.AddBenefitsTPBIPremSI500K();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIPremSI1M }
     *
     */
    public Root.Quote.AddBenefitsTPBIPremSI1M createRootQuoteAddBenefitsTPBIPremSI1M() {
        return new Root.Quote.AddBenefitsTPBIPremSI1M();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIPremSI2M }
     *
     */
    public Root.Quote.AddBenefitsTPBIPremSI2M createRootQuoteAddBenefitsTPBIPremSI2M() {
        return new Root.Quote.AddBenefitsTPBIPremSI2M();
    }

    /**
     * Create an instance of {@link Root.Quote.AddBenefitsTPBIPremSI3M }
     *
     */
    public Root.Quote.AddBenefitsTPBIPremSI3M createRootQuoteAddBenefitsTPBIPremSI3M() {
        return new Root.Quote.AddBenefitsTPBIPremSI3M();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayCoverODCollisionSIType1 }
     *
     */
    public Root.Quote.ArrayCoverODCollisionSIType1 createRootQuoteArrayCoverODCollisionSIType1() {
        return new Root.Quote.ArrayCoverODCollisionSIType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayCoverODCollisionSIType2Plus }
     *
     */
    public Root.Quote.ArrayCoverODCollisionSIType2Plus createRootQuoteArrayCoverODCollisionSIType2Plus() {
        return new Root.Quote.ArrayCoverODCollisionSIType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverCompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25CompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30CompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem0XsAnyWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem0XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem0XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem0XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverNoCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyDriverNoCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyDriverNoCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25CompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25CompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25CompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25NoCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver25NoCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver25NoCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30CompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30CompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30CompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType2 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30NoCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType3 createRootQuoteArrayPrem0XsPanelWorkshopAnyOver30NoCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopAnyOver30NoCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem0XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType2 createRootQuoteArrayPrem0XsPanelWorkshopNamedCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType3 createRootQuoteArrayPrem0XsPanelWorkshopNamedCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem0XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType2 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType2 createRootQuoteArrayPrem0XsPanelWorkshopNamedNoCompType2() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType2();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType3 }
     *
     */
    public Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType3 createRootQuoteArrayPrem0XsPanelWorkshopNamedNoCompType3() {
        return new Root.Quote.ArrayPrem0XsPanelWorkshopNamedNoCompType3();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25CompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30CompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem1000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem1000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25CompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30CompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem1000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem1000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem1000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem1000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25CompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30CompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem10000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25CompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30CompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem10000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem10000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsAnyWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem2000XsPanelWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem3000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem3000XsAnyWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem3000XsAnyWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsAnyWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem3000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem3000XsPanelWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem3000XsPanelWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem3000XsPanelWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1 createRootQuoteArrayPrem5000XsAnyWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem5000XsAnyWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem5000XsAnyWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsAnyWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverNoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyDriverNoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyDriverNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25CompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25CompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25CompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25NoCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25NoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver25NoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver25NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30CompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30CompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30CompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30CompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30NoCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30NoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopAnyOver30NoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopAnyOver30NoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopNamedCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopNamedCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopNamedCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1 }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1 createRootQuoteArrayPrem5000XsPanelWorkshopNamedNoCompType1() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType2Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType2Plus createRootQuoteArrayPrem5000XsPanelWorkshopNamedNoCompType2Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType2Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType3Plus }
     *
     */
    public Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType3Plus createRootQuoteArrayPrem5000XsPanelWorkshopNamedNoCompType3Plus() {
        return new Root.Quote.ArrayPrem5000XsPanelWorkshopNamedNoCompType3Plus();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPremRSANonType1 }
     *
     */
    public Root.Quote.ArrayPremRSANonType1 createRootQuoteArrayPremRSANonType1() {
        return new Root.Quote.ArrayPremRSANonType1();
    }

    /**
     * Create an instance of {@link Root.Quote.ArrayPremRSAType1 }
     *
     */
    public Root.Quote.ArrayPremRSAType1 createRootQuoteArrayPremRSAType1() {
        return new Root.Quote.ArrayPremRSAType1();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesDataValidation }
     *
     */
    public Root.Quote.BusinessRulesDataValidation createRootQuoteBusinessRulesDataValidation() {
        return new Root.Quote.BusinessRulesDataValidation();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesErrorMessages }
     *
     */
    public Root.Quote.BusinessRulesErrorMessages createRootQuoteBusinessRulesErrorMessages() {
        return new Root.Quote.BusinessRulesErrorMessages();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesMaxAuthorisationLevel }
     *
     */
    public Root.Quote.BusinessRulesMaxAuthorisationLevel createRootQuoteBusinessRulesMaxAuthorisationLevel() {
        return new Root.Quote.BusinessRulesMaxAuthorisationLevel();
    }

    /**
     * Create an instance of {@link Root.Quote.BusinessRulesResult }
     *
     */
    public Root.Quote.BusinessRulesResult createRootQuoteBusinessRulesResult() {
        return new Root.Quote.BusinessRulesResult();
    }

    /**
     * Create an instance of {@link Root.Quote.CarDefaultValueFinal }
     *
     */
    public Root.Quote.CarDefaultValueFinal createRootQuoteCarDefaultValueFinal() {
        return new Root.Quote.CarDefaultValueFinal();
    }

    /**
     * Create an instance of {@link Root.Quote.CarTypeCompulsoryInsuranceCode }
     *
     */
    public Root.Quote.CarTypeCompulsoryInsuranceCode createRootQuoteCarTypeCompulsoryInsuranceCode() {
        return new Root.Quote.CarTypeCompulsoryInsuranceCode();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverBailBondSI }
     *
     */
    public Root.Quote.CoverBailBondSI createRootQuoteCoverBailBondSI() {
        return new Root.Quote.CoverBailBondSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverDriverPlan }
     *
     */
    public Root.Quote.CoverDriverPlan createRootQuoteCoverDriverPlan() {
        return new Root.Quote.CoverDriverPlan();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverIncludesCompulsoryFlag }
     *
     */
    public Root.Quote.CoverIncludesCompulsoryFlag createRootQuoteCoverIncludesCompulsoryFlag() {
        return new Root.Quote.CoverIncludesCompulsoryFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverMedicalExpensesSI }
     *
     */
    public Root.Quote.CoverMedicalExpensesSI createRootQuoteCoverMedicalExpensesSI() {
        return new Root.Quote.CoverMedicalExpensesSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODCollisionSI }
     *
     */
    public Root.Quote.CoverODCollisionSI createRootQuoteCoverODCollisionSI() {
        return new Root.Quote.CoverODCollisionSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODDeductibleAmount }
     *
     */
    public Root.Quote.CoverODDeductibleAmount createRootQuoteCoverODDeductibleAmount() {
        return new Root.Quote.CoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODFireTheftSI }
     *
     */
    public Root.Quote.CoverODFireTheftSI createRootQuoteCoverODFireTheftSI() {
        return new Root.Quote.CoverODFireTheftSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODNaturalDisasterSI }
     *
     */
    public Root.Quote.CoverODNaturalDisasterSI createRootQuoteCoverODNaturalDisasterSI() {
        return new Root.Quote.CoverODNaturalDisasterSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverODPersonalAccidentSI }
     *
     */
    public Root.Quote.CoverODPersonalAccidentSI createRootQuoteCoverODPersonalAccidentSI() {
        return new Root.Quote.CoverODPersonalAccidentSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPADriversSI }
     *
     */
    public Root.Quote.CoverPADriversSI createRootQuoteCoverPADriversSI() {
        return new Root.Quote.CoverPADriversSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverPAPassengersSI }
     *
     */
    public Root.Quote.CoverPAPassengersSI createRootQuoteCoverPAPassengersSI() {
        return new Root.Quote.CoverPAPassengersSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPBodilyInjuryAccidentSI }
     *
     */
    public Root.Quote.CoverTPBodilyInjuryAccidentSI createRootQuoteCoverTPBodilyInjuryAccidentSI() {
        return new Root.Quote.CoverTPBodilyInjuryAccidentSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryBodilyInjurySI }
     *
     */
    public Root.Quote.CoverTPVoluntaryBodilyInjurySI createRootQuoteCoverTPVoluntaryBodilyInjurySI() {
        return new Root.Quote.CoverTPVoluntaryBodilyInjurySI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTPVoluntaryPropertyDamageSI }
     *
     */
    public Root.Quote.CoverTPVoluntaryPropertyDamageSI createRootQuoteCoverTPVoluntaryPropertyDamageSI() {
        return new Root.Quote.CoverTPVoluntaryPropertyDamageSI();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverTerritorialSelection }
     *
     */
    public Root.Quote.CoverTerritorialSelection createRootQuoteCoverTerritorialSelection() {
        return new Root.Quote.CoverTerritorialSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverVoluntaryType }
     *
     */
    public Root.Quote.CoverVoluntaryType createRootQuoteCoverVoluntaryType() {
        return new Root.Quote.CoverVoluntaryType();
    }

    /**
     * Create an instance of {@link Root.Quote.CoverWorkshopSelection }
     *
     */
    public Root.Quote.CoverWorkshopSelection createRootQuoteCoverWorkshopSelection() {
        return new Root.Quote.CoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.CurrentCode }
     *
     */
    public Root.Quote.CurrentCode createRootQuoteCurrentCode() {
        return new Root.Quote.CurrentCode();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverDriverPlan }
     *
     */
    public Root.Quote.DefaultCoverDriverPlan createRootQuoteDefaultCoverDriverPlan() {
        return new Root.Quote.DefaultCoverDriverPlan();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverIncludesCompulsoryFlag }
     *
     */
    public Root.Quote.DefaultCoverIncludesCompulsoryFlag createRootQuoteDefaultCoverIncludesCompulsoryFlag() {
        return new Root.Quote.DefaultCoverIncludesCompulsoryFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverODDeductibleAmount }
     *
     */
    public Root.Quote.DefaultCoverODDeductibleAmount createRootQuoteDefaultCoverODDeductibleAmount() {
        return new Root.Quote.DefaultCoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverVoluntaryType }
     *
     */
    public Root.Quote.DefaultCoverVoluntaryType createRootQuoteDefaultCoverVoluntaryType() {
        return new Root.Quote.DefaultCoverVoluntaryType();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultCoverWorkshopSelection }
     *
     */
    public Root.Quote.DefaultCoverWorkshopSelection createRootQuoteDefaultCoverWorkshopSelection() {
        return new Root.Quote.DefaultCoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.DefaultPremiumVoluntaryBeforeTaxes }
     *
     */
    public Root.Quote.DefaultPremiumVoluntaryBeforeTaxes createRootQuoteDefaultPremiumVoluntaryBeforeTaxes() {
        return new Root.Quote.DefaultPremiumVoluntaryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.FaultClaimsForRating }
     *
     */
    public Root.Quote.FaultClaimsForRating createRootQuoteFaultClaimsForRating() {
        return new Root.Quote.FaultClaimsForRating();
    }

    /**
     * Create an instance of {@link Root.Quote.FaultIncurred }
     *
     */
    public Root.Quote.FaultIncurred createRootQuoteFaultIncurred() {
        return new Root.Quote.FaultIncurred();
    }

    /**
     * Create an instance of {@link Root.Quote.MonthlyNoDepositPaymentLoadingFactor }
     *
     */
    public Root.Quote.MonthlyNoDepositPaymentLoadingFactor createRootQuoteMonthlyNoDepositPaymentLoadingFactor() {
        return new Root.Quote.MonthlyNoDepositPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.NonAnnualPaymentLoadingFactor }
     *
     */
    public Root.Quote.NonAnnualPaymentLoadingFactor createRootQuoteNonAnnualPaymentLoadingFactor() {
        return new Root.Quote.NonAnnualPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyPaymentFrequency }
     *
     */
    public Root.Quote.PolicyPaymentFrequency createRootQuotePolicyPaymentFrequency() {
        return new Root.Quote.PolicyPaymentFrequency();
    }

    /**
     * Create an instance of {@link Root.Quote.PolicyProductVersion }
     *
     */
    public Root.Quote.PolicyProductVersion createRootQuotePolicyProductVersion() {
        return new Root.Quote.PolicyProductVersion();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsCalculatedNCBPct }
     *
     */
    public Root.Quote.PremDetailsCalculatedNCBPct createRootQuotePremDetailsCalculatedNCBPct() {
        return new Root.Quote.PremDetailsCalculatedNCBPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsRenewalAdjustmentPct }
     *
     */
    public Root.Quote.PremDetailsRenewalAdjustmentPct createRootQuotePremDetailsRenewalAdjustmentPct() {
        return new Root.Quote.PremDetailsRenewalAdjustmentPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTariffMaximum }
     *
     */
    public Root.Quote.PremDetailsTariffMaximum createRootQuotePremDetailsTariffMaximum() {
        return new Root.Quote.PremDetailsTariffMaximum();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTariffMinimum }
     *
     */
    public Root.Quote.PremDetailsTariffMinimum createRootQuotePremDetailsTariffMinimum() {
        return new Root.Quote.PremDetailsTariffMinimum();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTechnicalAdjusted }
     *
     */
    public Root.Quote.PremDetailsTechnicalAdjusted createRootQuotePremDetailsTechnicalAdjusted() {
        return new Root.Quote.PremDetailsTechnicalAdjusted();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsTechnicalAuto }
     *
     */
    public Root.Quote.PremDetailsTechnicalAuto createRootQuotePremDetailsTechnicalAuto() {
        return new Root.Quote.PremDetailsTechnicalAuto();
    }

    /**
     * Create an instance of {@link Root.Quote.PremDetailsVoluntaryDiscountPct }
     *
     */
    public Root.Quote.PremDetailsVoluntaryDiscountPct createRootQuotePremDetailsVoluntaryDiscountPct() {
        return new Root.Quote.PremDetailsVoluntaryDiscountPct();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBailBond }
     *
     */
    public Root.Quote.PremFinalBailBond createRootQuotePremFinalBailBond() {
        return new Root.Quote.PremFinalBailBond();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBasic123 }
     *
     */
    public Root.Quote.PremFinalBasic123 createRootQuotePremFinalBasic123() {
        return new Root.Quote.PremFinalBasic123();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalBasic5 }
     *
     */
    public Root.Quote.PremFinalBasic5 createRootQuotePremFinalBasic5() {
        return new Root.Quote.PremFinalBasic5();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCompulsoryBeforeTaxes }
     *
     */
    public Root.Quote.PremFinalCompulsoryBeforeTaxes createRootQuotePremFinalCompulsoryBeforeTaxes() {
        return new Root.Quote.PremFinalCompulsoryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCompulsoryCommission }
     *
     */
    public Root.Quote.PremFinalCompulsoryCommission createRootQuotePremFinalCompulsoryCommission() {
        return new Root.Quote.PremFinalCompulsoryCommission();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCore123 }
     *
     */
    public Root.Quote.PremFinalCore123 createRootQuotePremFinalCore123() {
        return new Root.Quote.PremFinalCore123();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalCore5 }
     *
     */
    public Root.Quote.PremFinalCore5 createRootQuotePremFinalCore5() {
        return new Root.Quote.PremFinalCore5();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalMedicalExpenses }
     *
     */
    public Root.Quote.PremFinalMedicalExpenses createRootQuotePremFinalMedicalExpenses() {
        return new Root.Quote.PremFinalMedicalExpenses();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalNCB }
     *
     */
    public Root.Quote.PremFinalNCB createRootQuotePremFinalNCB() {
        return new Root.Quote.PremFinalNCB();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalNamedDriverDiscount }
     *
     */
    public Root.Quote.PremFinalNamedDriverDiscount createRootQuotePremFinalNamedDriverDiscount() {
        return new Root.Quote.PremFinalNamedDriverDiscount();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalODDeductible }
     *
     */
    public Root.Quote.PremFinalODDeductible createRootQuotePremFinalODDeductible() {
        return new Root.Quote.PremFinalODDeductible();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalPADrivers }
     *
     */
    public Root.Quote.PremFinalPADrivers createRootQuotePremFinalPADrivers() {
        return new Root.Quote.PremFinalPADrivers();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalPAPassengers }
     *
     */
    public Root.Quote.PremFinalPAPassengers createRootQuotePremFinalPAPassengers() {
        return new Root.Quote.PremFinalPAPassengers();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalRSABeforeTaxes }
     *
     */
    public Root.Quote.PremFinalRSABeforeTaxes createRootQuotePremFinalRSABeforeTaxes() {
        return new Root.Quote.PremFinalRSABeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryBasic }
     *
     */
    public Root.Quote.PremFinalVoluntaryBasic createRootQuotePremFinalVoluntaryBasic() {
        return new Root.Quote.PremFinalVoluntaryBasic();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryBeforeTaxes }
     *
     */
    public Root.Quote.PremFinalVoluntaryBeforeTaxes createRootQuotePremFinalVoluntaryBeforeTaxes() {
        return new Root.Quote.PremFinalVoluntaryBeforeTaxes();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryCommission }
     *
     */
    public Root.Quote.PremFinalVoluntaryCommission createRootQuotePremFinalVoluntaryCommission() {
        return new Root.Quote.PremFinalVoluntaryCommission();
    }

    /**
     * Create an instance of {@link Root.Quote.PremFinalVoluntaryDiscount }
     *
     */
    public Root.Quote.PremFinalVoluntaryDiscount createRootQuotePremFinalVoluntaryDiscount() {
        return new Root.Quote.PremFinalVoluntaryDiscount();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechAddons }
     *
     */
    public Root.Quote.PremTechAddons createRootQuotePremTechAddons() {
        return new Root.Quote.PremTechAddons();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechCar }
     *
     */
    public Root.Quote.PremTechCar createRootQuotePremTechCar() {
        return new Root.Quote.PremTechCar();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechCoverODDeductibleAmount }
     *
     */
    public Root.Quote.PremTechCoverODDeductibleAmount createRootQuotePremTechCoverODDeductibleAmount() {
        return new Root.Quote.PremTechCoverODDeductibleAmount();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechCoverWorkshopSelection }
     *
     */
    public Root.Quote.PremTechCoverWorkshopSelection createRootQuotePremTechCoverWorkshopSelection() {
        return new Root.Quote.PremTechCoverWorkshopSelection();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechDriver }
     *
     */
    public Root.Quote.PremTechDriver createRootQuotePremTechDriver() {
        return new Root.Quote.PremTechDriver();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechFixedCost }
     *
     */
    public Root.Quote.PremTechFixedCost createRootQuotePremTechFixedCost() {
        return new Root.Quote.PremTechFixedCost();
    }

    /**
     * Create an instance of {@link Root.Quote.PremTechMin }
     *
     */
    public Root.Quote.PremTechMin createRootQuotePremTechMin() {
        return new Root.Quote.PremTechMin();
    }

    /**
     * Create an instance of {@link Root.Quote.QuarterlyPaymentLoadingFactor }
     *
     */
    public Root.Quote.QuarterlyPaymentLoadingFactor createRootQuoteQuarterlyPaymentLoadingFactor() {
        return new Root.Quote.QuarterlyPaymentLoadingFactor();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleType }
     *
     */
    public Root.Quote.UWVehicleType createRootQuoteUWVehicleType() {
        return new Root.Quote.UWVehicleType();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleTypeUpdateFlag }
     *
     */
    public Root.Quote.UWVehicleTypeUpdateFlag createRootQuoteUWVehicleTypeUpdateFlag() {
        return new Root.Quote.UWVehicleTypeUpdateFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.UWVehicleTypeWarningFlag }
     *
     */
    public Root.Quote.UWVehicleTypeWarningFlag createRootQuoteUWVehicleTypeWarningFlag() {
        return new Root.Quote.UWVehicleTypeWarningFlag();
    }

    /**
     * Create an instance of {@link Root.Quote.VehicleInspectionLimit }
     *
     */
    public Root.Quote.VehicleInspectionLimit createRootQuoteVehicleInspectionLimit() {
        return new Root.Quote.VehicleInspectionLimit();
    }

}
