---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
     dialect : org.hibernate.dialect.SQLServer2012Dialect
     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
     logSql: false
     formatSql: true
     pooled: true
     jmxExport: true
     properties:
        jmxEnabled : true
        initialSize : 10
        maxActive : 100
        minIdle : 5
        maxIdle : 25
        maxWait : 10000
        maxAge : 600000
        timeBetweenEvictionRunsMillis : 5000
        minEvictableIdleTimeMillis : 60000
        validationQuery : "SELECT 1"
        validationQueryTimeout : 3
        validationInterval : 15000
        testOnBorrow : true
        testWhileIdle : true
        testOnReturn : false
        jdbcInterceptors : "ConnectionState;StatementCache(max=200)"
environments:
    development:
        dataSource:
            dbCreate: update
            username: DevInsureUser
            password: M9Eg?0H$p6VHJYlBLFae
            url: jdbc:sqlserver://sin-dev-roojai.database.windows.net:1433;database=dev-insure;autoReconnect=true
    test:
        dataSource:
            dbCreate: update
            username: roojaiuat
            password: AF3wMrKuGH
            url: jdbc:sqlserver://sqlfg-uat-insure-roojai.database.windows.net:1433;database=uat-insure-roojai;autoReconnect=true
    production:
        dataSource:
            dbCreate: update
            username: roojaiprod
            password: WSmBZCdUa$
            url: jdbc:sqlserver://sqlfg-insure-roojai.database.windows.net:1433;database=insure-roojaidb;autoReconnect=true

---
---
grails:
    profile: web
    codegen:
        defaultPackage: com
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    cors:
        enabled: true
        mappings:
            /api/**: inherit
endpoints:
    jmx:
        unique-names: true
#https://github.com/grails/grails-core/issues/9424
spring:
    jmx:
        enabled: false
#for about page
version: '#version#'
releaseDate: '#releaseDate#'